import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Navigation from "@/components/navigation";
import { motion } from "framer-motion";

export default function Projects() {
  return (
    <>
      <Head>
        <title>About | Victor Bianconi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.main
        exit={{ opacity: 0 }}
        transition={{ duration: 0.3 }}
        key="projects"
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        className="page"
      >
        <div className="page__main-container">
          <motion.h1
            animate={{ opacity: 1 }}
            initial={{ opacity: 0 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.3 }}
            className="text-5xl font-bold mb-9"
          >
            About me
          </motion.h1>
          <motion.p
            animate={{ opacity: 1 }}
            initial={{ opacity: 0 }}
            transition={{ duration: 0.3 }}
            className="text-3xl leading-10 mb-6"
          >
            I'm a 23-year-old from Italy with over 15 years of experience in
            designing and building things, including coding since age 8 and
            graphic design since age 13. I can help you create professional and
            functional websites that meet both your customers' needs and your
            business objectives.
          </motion.p>
          <motion.p
            animate={{ opacity: 1 }}
            initial={{ opacity: 0 }}
            transition={{ duration: 0.3, delay: 0.1 }}
            className="text-3xl leading-10 mb-6"
          >
            All the websites I create are meant not only to look good and
            <span className="font-bold"> enhance your brand</span>, but to{" "}
            <span className="font-bold">save time</span> for you and your
            customers, as well as improve the performance of your business.
          </motion.p>{" "}
          <motion.p
            animate={{ opacity: 1 }}
            initial={{ opacity: 0 }}
            transition={{ duration: 0.3, delay: 0.2 }}
            className="text-3xl leading-10"
          >
            In addition to web development, I'm passionate about topics such as
            marketing, branding, and entrepreneurship.
          </motion.p>
        </div>
      </motion.main>
    </>
  );
}
